name: PDFium - WASM

on: [push]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "Ubuntu Latest", os: "ubuntu-20.04", target: "wasm" }
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2

      - name: Setup GIT user
        run: |
          git config --global user.name "Paulo Coutinho"
          git config --global user.email "paulo@prsolucoes.com"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade PIP
        run: python3 -m pip install --upgrade pip setuptools wheel

      - name: Display Python version
        run: python3 --version

      - name: Display PIP version
        run: pip3 --version

      - name: Python requirements
        run: pip3 install -r requirements.txt --user

      - name: Docker build
        run: docker build -t pdfium-wasm -f docker/wasm/Dockerfile docker/wasm

      - name: Docker test
        run: docker run -v ${PWD}:/app -i -t=false pdfium-wasm echo "test"

      - name: PDFium
        run: docker run -v ${PWD}:/app -i -t=false pdfium-wasm python3 make.py run build-pdfium-${{ matrix.config.target }}

      - name: Patch
        run: docker run -v ${PWD}:/app -i -t=false pdfium-wasm python3 make.py run patch-${{ matrix.config.target }}

      - name: Build
        run: docker run -v ${PWD}:/app -i -t=false pdfium-wasm python3 make.py run build-${{ matrix.config.target }}

      - name: Install
        run: docker run -v ${PWD}:/app -i -t=false pdfium-wasm python3 make.py run install-${{ matrix.config.target }}

      - name: Test
        run: docker run -v ${PWD}:/app -i -t=false pdfium-wasm python3 make.py run test-${{ matrix.config.target }}

      - name: Generate
        run: docker run -v ${PWD}:/app -i -t=false pdfium-wasm python3 make.py run generate-${{ matrix.config.target }}

      - name: Archive
        run: docker run -v ${PWD}:/app -i -t=false pdfium-wasm python3 make.py run archive-${{ matrix.config.target }}
        if: startsWith(github.ref, 'refs/tags/')

      - name: Save
        uses: actions/upload-artifact@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: artifact-${{ matrix.config.target }}
          path: ${{ matrix.config.target }}.tgz

      - name: Publish to web
        run: |
          sudo chmod -R 777 build/linux
          python3 make.py run publish-${{ matrix.config.target }}
        if: startsWith(github.ref, 'refs/tags/')

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Load
        uses: actions/download-artifact@v2
        with:
          name: artifact-wasm
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: wasm.tgz
          asset_name: wasm.tgz
          asset_content_type: application/tar+gzip
